### ISSUE TITLE
Update version number

### ISSUE THREAD

**Issue by landonmr** [Moujarkash/bugsnag-crashlytics#12]
@Moujarkash Are you going to publish the updated code to pub.dev?

**Comment by Moujarkash** [comment]
Yes, this weekend

**Comment by landonmr** [comment]
Thank you very much!

**Comment by landonmr** [comment]
any update? pub.dev version still seems to be  on `0.0.7`

**Comment by Moujarkash** [comment]
@landonmr done
the version is 1.0.0 now

**Comment by Moujarkash** [comment]
https://pub.dev/packages/bugsnag_crashlytics
No it's 1.0.0

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
