### ISSUE TITLE
Native android error when building the plugin

### ISSUE THREAD

**Issue by svprdga** [Moujarkash/bugsnag-crashlytics#14]
## Steps to reproduce

1. Create a flutter app with `bugsnag_crashlytics: ^1.0.0`
2. Run the app in Android

## Expected result

The app launches normally

## Actual result

There is an error related with a dependency:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':bugsnag_crashlytics'.
> > Could not resolve all artifacts for configuration ':bugsnag_crashlytics:classpath'.
>    > Could not find com.bugsnag:bugsnag-android-gradle-plugin:5.9.5.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/bugsnag/bugsnag-android-gradle-plugin/5.9.5/bugsnag-android-gradle-plugin-5.9.5.pom
>        - https://jcenter.bintray.com/com/bugsnag/bugsnag-android-gradle-plugin/5.9.5/bugsnag-android-gradle-plugin-5.9.5.pom
>      Required by:
>          project :bugsnag_crashlytics
> > Could not get unknown property 'android' for project ':bugsnag_crashlytics' of type org.gradle.api.Project.
>

**Comment by fede1295** [comment]
Same problem for me with 1.0.0 version, while with 0.0.7 everything works fine

**Comment by Moujarkash** [comment]
@humbugz I will check it soon

**Comment by BananaNeil** [comment]
I'm also experiencing this same issue!

**Comment by jugal-k-j** [comment]
Even after updating it with the above configuration, I still have the same issue, @Moujarkash  Could you please check it?

**Comment by jpirovano** [comment]
I think the problem is with the mvn repo, its returning 404/403

**Comment by jpirovano** [comment]
@Moujarkash the repo jcenter is not live anymore, can you change to mavenCentral?

**Comment by rashmisridar** [comment]
Even I'm phasing the same issue. What is the solution for it? Thanks
