### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by robertflesch** [Moujarkash/bugsnag-crashlytics#7]
So running into some issues trying to get my app connected to bugsnag.
First off, you ask for an androidApiKey, is this the key that comes from Google Cloud Platform? Who exactly issues this key?
So I am using the key from GCP and here is the code I use to initialize it.
'''
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  BugsnagCrashlytics.instance.register(
      androidApiKey: "MY_GOOGLE_API_KEY",
      iosApiKey: "IOS_API_KEY",
      releaseStage: 'RELEASE_STAGE',
      appVersion: 'APP_VERSION');

  FlutterError.onError = BugsnagCrashlytics.instance.recordFlutterError;

  runZoned(() {
    runApp(
      ChangeNotifierProvider(
          create: (_) => ThemeProvider(isLightTheme: true),
          child: MyApp()
      ));
  }, onError: BugsnagCrashlytics.instance.recordError);
}
'''
and this is what I see in the logs
'''
W/Bugsnag ( 7299): Invalid configuration. apiKey should be a 32-character hexademical string, got "3d5855d9c4567d4ah7d03bt5tfd10247"
W/Bugsnag ( 7299): Invalid configuration. apiKey should be a 32-character hexademical string, got "MY_GOOGLE_API_KEY"
I/TetheringManager( 7299): registerTetheringEventCallback:myApp.Name
D/Bugsnag ( 7299): Plugin 'com.bugsnag.android.BugsnagReactNativePlugin' is not on the classpath - functionality will not be enabled.
D/Bugsnag ( 7299): Received NDK message com.bugsnag.android.StateEvent$Install@959de6a
W/Bugsnag ( 7299): Received message before INSTALL: com.bugsnag.android.StateEvent$AddBreadcrumb@d042f5b
W/BugsnagNDK( 7299): Initialization complete!
D/Bugsnag ( 7299): Received NDK message com.bugsnag.android.StateEvent$UpdateContext@d2f7736
D/Bugsnag ( 7299): Received NDK message com.bugsnag.android.StateEvent$DeliverPending@d4c6637
D/Bugsnag ( 7299): Received NDK message com.bugsnag.android.StateEvent$UpdateUser@63677a4
I/Bugsnag ( 7299): Initialised NDK Plugin
I/Bugsnag ( 7299): Initialised ANR Plugin
'''

Any clues? @Moujarkash or others?

**Comment by Moujarkash** [comment]
Hi
You should get the android key from bugsnag dashboard, you should create a project for android and ios and get the keys

**Comment by robertflesch** [comment]
Thanks, that helped with first issue.

Do I need to worry about 
D/Bugsnag ( 7299): Plugin 'com.bugsnag.android.BugsnagReactNativePlugin' is not on the classpath - functionality will not be enabled.

Also is there anyway to use breadcrumbs?

@Moujarkash

**Comment by Moujarkash** [comment]
Fixed
